// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shop_hubLaps.Models;

#nullable disable

namespace shop_hubLaps.Migrations.DataModelMigrations
{
    [DbContext(typeof(DataModel))]
    [Migration("20241020122802_UpdateDataModel")]
    partial class UpdateDataModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("shop_hubLaps.Models.BinhLuan", b =>
                {
                    b.Property<int>("mabinhluan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mabinhluan"));

                    b.Property<int>("TinTucmatin")
                        .HasColumnType("int");

                    b.Property<int?>("matin")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ngaybinhluan")
                        .HasColumnType("datetime2");

                    b.Property<string>("noidung")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<string>("ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("trangthai")
                        .HasColumnType("bit");

                    b.Property<int?>("vote")
                        .HasColumnType("int");

                    b.HasKey("mabinhluan");

                    b.HasIndex("TinTucmatin");

                    b.ToTable("BinhLuan");
                });

            modelBuilder.Entity("shop_hubLaps.Models.ChuDe", b =>
                {
                    b.Property<int>("machude")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("machude"));

                    b.Property<string>("hinh")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("tenchude")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("machude");

                    b.ToTable("ChuDe");
                });

            modelBuilder.Entity("shop_hubLaps.Models.DanhGia", b =>
                {
                    b.Property<int>("madanhgia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("madanhgia"));

                    b.Property<int>("Laptopmalaptop")
                        .HasColumnType("int");

                    b.Property<int?>("malaptop")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ngaydanhgia")
                        .HasColumnType("datetime2");

                    b.Property<string>("noidung")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<string>("ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("trangthai")
                        .HasColumnType("bit");

                    b.Property<int?>("vote")
                        .HasColumnType("int");

                    b.HasKey("madanhgia");

                    b.HasIndex("Laptopmalaptop");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("shop_hubLaps.Models.DonHang", b =>
                {
                    b.Property<int>("madon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("madon"));

                    b.Property<bool?>("giaohang")
                        .HasColumnType("bit");

                    b.Property<string>("makh")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("ngaydat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ngaygiao")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("thanhtoan")
                        .HasColumnType("bit");

                    b.Property<string>("tinhtrang")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("madon");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("shop_hubLaps.Models.Hang", b =>
                {
                    b.Property<int>("mahang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mahang"));

                    b.Property<string>("hinh")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("tenhang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("mahang");

                    b.ToTable("Hang");
                });

            modelBuilder.Entity("shop_hubLaps.Models.Laptop", b =>
                {
                    b.Property<int>("malaptop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("malaptop"));

                    b.Property<int>("Hangmahang")
                        .HasColumnType("int");

                    b.Property<int>("NhuCaumanhucau")
                        .HasColumnType("int");

                    b.Property<string>("cpu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("giaban")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("gpu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("hardware")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("hinh")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)");

                    b.Property<int?>("mahang")
                        .HasColumnType("int");

                    b.Property<string>("manhinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("manhucau")
                        .HasColumnType("int");

                    b.Property<string>("mota")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<DateTime?>("ngaycapnhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("pin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ram")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("soluongton")
                        .HasColumnType("int");

                    b.Property<string>("tenlaptop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("trangthai")
                        .HasColumnType("bit");

                    b.HasKey("malaptop");

                    b.HasIndex("Hangmahang");

                    b.HasIndex("NhuCaumanhucau");

                    b.ToTable("Laptop");
                });

            modelBuilder.Entity("shop_hubLaps.Models.LienHe", b =>
                {
                    b.Property<int>("malienhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("malienhe"));

                    b.Property<string>("dienthoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("varchar(254)");

                    b.Property<string>("hoten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("noidung")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<bool?>("trangthai")
                        .HasColumnType("bit");

                    b.Property<string>("website")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("malienhe");

                    b.ToTable("LienHe");
                });

            modelBuilder.Entity("shop_hubLaps.Models.MetaLaptop", b =>
                {
                    b.Property<int>("mameta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mameta"));

                    b.Property<int>("Laptopmalaptop")
                        .HasColumnType("int");

                    b.Property<string>("keymeta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("malaptop")
                        .HasColumnType("int");

                    b.Property<string>("valuemeta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("mameta");

                    b.HasIndex("Laptopmalaptop");

                    b.ToTable("MetaLaptop");
                });

            modelBuilder.Entity("shop_hubLaps.Models.NhuCau", b =>
                {
                    b.Property<int>("manhucau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("manhucau"));

                    b.Property<string>("tennhucau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("manhucau");

                    b.ToTable("NhuCau");
                });

            modelBuilder.Entity("shop_hubLaps.Models.QuangCao", b =>
                {
                    b.Property<int>("maqc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("maqc"));

                    b.Property<string>("hinhnen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("link")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ngaybatdau")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("ngayhethan")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("tencongty")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("tenqc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("trangthai")
                        .HasColumnType("bit");

                    b.HasKey("maqc");

                    b.ToTable("QuangCao");
                });

            modelBuilder.Entity("shop_hubLaps.Models.TinTuc", b =>
                {
                    b.Property<int>("matin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("matin"));

                    b.Property<int>("ChuDemachude")
                        .HasColumnType("int");

                    b.Property<string>("hinhnen")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)");

                    b.Property<int?>("luotxem")
                        .HasColumnType("int");

                    b.Property<int?>("machude")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ngaycapnhat")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("noidung")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("tieude")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("tomtat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("xuatban")
                        .HasColumnType("bit");

                    b.HasKey("matin");

                    b.HasIndex("ChuDemachude");

                    b.ToTable("TinTuc");
                });

            modelBuilder.Entity("shop_hubLaps.Models.BinhLuan", b =>
                {
                    b.HasOne("shop_hubLaps.Models.TinTuc", "TinTuc")
                        .WithMany("BinhLuans")
                        .HasForeignKey("TinTucmatin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TinTuc");
                });

            modelBuilder.Entity("shop_hubLaps.Models.DanhGia", b =>
                {
                    b.HasOne("shop_hubLaps.Models.Laptop", "Laptop")
                        .WithMany("DanhGias")
                        .HasForeignKey("Laptopmalaptop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laptop");
                });

            modelBuilder.Entity("shop_hubLaps.Models.Laptop", b =>
                {
                    b.HasOne("shop_hubLaps.Models.Hang", "Hang")
                        .WithMany("Laptops")
                        .HasForeignKey("Hangmahang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("shop_hubLaps.Models.NhuCau", "NhuCau")
                        .WithMany("Laptops")
                        .HasForeignKey("NhuCaumanhucau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hang");

                    b.Navigation("NhuCau");
                });

            modelBuilder.Entity("shop_hubLaps.Models.MetaLaptop", b =>
                {
                    b.HasOne("shop_hubLaps.Models.Laptop", "Laptop")
                        .WithMany("MetaLaptops")
                        .HasForeignKey("Laptopmalaptop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laptop");
                });

            modelBuilder.Entity("shop_hubLaps.Models.TinTuc", b =>
                {
                    b.HasOne("shop_hubLaps.Models.ChuDe", "ChuDe")
                        .WithMany("TinTucs")
                        .HasForeignKey("ChuDemachude")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuDe");
                });

            modelBuilder.Entity("shop_hubLaps.Models.ChuDe", b =>
                {
                    b.Navigation("TinTucs");
                });

            modelBuilder.Entity("shop_hubLaps.Models.Hang", b =>
                {
                    b.Navigation("Laptops");
                });

            modelBuilder.Entity("shop_hubLaps.Models.Laptop", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("MetaLaptops");
                });

            modelBuilder.Entity("shop_hubLaps.Models.NhuCau", b =>
                {
                    b.Navigation("Laptops");
                });

            modelBuilder.Entity("shop_hubLaps.Models.TinTuc", b =>
                {
                    b.Navigation("BinhLuans");
                });
#pragma warning restore 612, 618
        }
    }
}
